{
 "title": "Freebox Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Informations Freebox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General informations",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "freebox_connection_ftth_sfp_alim_ok",
     "legendFormat": "SFP Alim OK"
    },
    {
     "expr": "freebox_connection_ftth_sfp_has_power_report",
     "legendFormat": "SFP Has power report"
    },
    {
     "expr": "freebox_connection_ftth_sfp_has_signal",
     "legendFormat": "SFP Has signal"
    },
    {
     "expr": "freebox_connection_ftth_sfp_link",
     "legendFormat": "SFP Link"
    },
    {
     "expr": "freebox_connection_ftth_sfp_present",
     "legendFormat": "SFP Present"
    }
   ]
  },
  {
   "title": "Températures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "freebox_system_temp_celsius", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Vitesse des ventilateurs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "freebox_system_fan_rpm", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "SFP ↓ Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "freebox_connection_ftth_sfp_rx_pwr_decibels",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP ↑ Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "freebox_connection_ftth_sfp_tx_pwr_decibels",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Débits ↓",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "freebox_net_down_bytes", "legendFormat": "DOWN" }
   ]
  },
  {
   "title": "Débits ↑",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "freebox_net_up_bytes", "legendFormat": "UP" }
   ]
  },
  {
   "title": "WiFi ↓",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "freebox_wifi_tx_rate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "WiFi ↑",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "freebox_wifi_rx_rate", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}