FROM golang:1.20

WORKDIR /

COPY . .

ADD https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz /usr/local

RUN set -x
RUN apt update
RUN apt install -y xz-utils
RUN xz -d -c /usr/local/upx-4.0.2-amd64_linux.tar.xz | tar -xOf - upx-4.0.2-amd64_linux/upx > /bin/upx
RUN chmod a+x /bin/upx
RUN go get -d -v .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o app .
RUN strip --strip-unneeded app
RUN upx app

FROM scratch

COPY --from=0 app /

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/app"]
