version: '3.7'

services:
  freebox_exporter:
    container_name: freebox_exporter
    image: ghcr.io/alois-gaucher/freebox-exporter:amd64
    command: -endpoint "http://192.168.1.254" -listen ":10001"
    restart: unless-stopped
    ports:
      - 10001:10001
    volumes:
      - ./token:/token
    environment:
      - HOME=token